<?php
$worldpay_currency_list = '<option value="EUR">Euro</option>
<option value="GBP">Pounds Sterling</option>
<option value="USD">US Dollar</option>
<option value="AFA">Afghani</option>
<option value="DZD">Algerian Dinar</option>
<option value="ARS">Argentine Peso</option>
<option value="AWG">Aruban Guilder</option>
<option value="AUD">Australian Dollar</option>
<option value="BSD">Bahamian Dollar</option>
<option value="BHD">Bahraini Dinar</option>
<option value="THB">Baht</option>
<option value="PAB">Balboa</option>
<option value="BBD">Barbados Dollar</option>
<option value="BZD">Belize Dollar</option>
<option value="BMD">Bermudian Dollar</option>
<option value="BOB">Boliviano</option>
<option value="BAD">Bosnian Dinar</option>
<option value="BIF">Burundi Franc</option>
<option value="BND">Brunei Dollar</option>
<option value="XOF">CFA Franc BCEAO</option>
<option value="XAF">CFA Franc BEAC</option>
<option value="XPF">CFP Franc</option>
<option value="KHR">Cambodia Riel</option>
<option value="CAD">Canadian Dollar</option>
<option value="CVE">Cape Verde Escudo</option>
<option value="KYD">Cayman Islands Dollar</option>
<option value="GHC">Cedi</option>
<option value="CLP">Chilean Peso</option>
<option value="COP">Colombian Peso</option>
<option value="KMF">Comoro Franc</option>
<option value="NIO">Cordoba Oro</option>
<option value="CRC">Costa Rican Colon</option>
<option value="HRK">Croatian Kuna</option>
<option value="CUP">Cuban Peso</option>
<option value="CYP">Cyprus Pound</option>
<option value="CZK">Czech Koruna</option>
<option value="GMD">Dalasi</option>
<option value="DKK">Danish Krone</option>
<option value="MKD">Denar</option>
<option value="DJF">Djibouti Franc</option>
<option value="STD">Dobra</option>
<option value="DOP">Dominican Peso</option>
<option value="XCD">East Caribbean Dollar</option>
<option value="ECS">Ecuador Sucre</option>
<option value="EGP">Egyptian Pound</option>
<option value="SVC">El Salvador Colon</option>
<option value="ETB">Ethiopian Birr</option>
<option value="FKP">Falkland Islands Pound</option>
<option value="HUF">Forint</option>
<option value="FJD">Fiji Dollar</option>
<option value="GIP">Gibraltar Pound</option>
<option value="HTG">Gourde</option>
<option value="PYG">Guarani</option>
<option value="GNF">Guinea Franc</option>
<option value="GWP">Guinea - Bissau Peso</option>
<option value="GYD">Guyana Dollar</option>
<option value="HKD">Hong Kong Dollar</option>
<option value="ISK">Iceland Krona</option>
<option value="INR">Indian Rupee</option>
<option value="IRR">Iranian Rial</option>
<option value="IQD">Iraqi Dinar</option>
<option value="JMD">Jamaican Dollar</option>
<option value="JOD">Jordanian Dinar</option>
<option value="KES">Kenyan Shilling</option>
<option value="EEK">Kroon</option>
<option value="KWD">Kuwaiti Dinar</option>
<option value="LAK">Kip</option>
<option value="LVL">Latvian Lats</option>
<option value="LBP">Lebanese Pound</option>
<option value="ALL">Lek</option>
<option value="HNL">Lempira</option>
<option value="SLL">Leone</option>
<option value="ROL">Leu</option>
<option value="BGL">Lev</option>
<option value="LSL">Loti</option>
<option value="LRD">Liberian Dollar</option>
<option value="LYD">Libyan Dinar</option>
<option value="LTL">Lithuanian Litas</option>
<option value="MWK">Kwacha</option>
<option value="MGF">Malagasy Franc</option>
<option value="MYR">Malaysian Ringitt</option>
<option value="MTL">Maltese Lira</option>
<option value="MUR">Mauritius Rupee</option>
<option value="MZM">Metical</option>
<option value="MXN">Mexico Peso</option>
<option value="MNT">Mongolia Tugrik</option>
<option value="MAD">Moroccan Dirham</option>
<option value="MMK">Myanmar Kyat</option>
<option value="NGN">Naira</option>
<option value="NAD">Namibian Dollar</option>
<option value="NPR">Nepalese Rupee</option>
<option value="ANG">Netherlands Antilles Guilder</option>
<option value="PGK">New Guinea Kina</option>
<option value="NZD">New Zealand Dollar</option>
<option value="AON">New Kwanza</option>
<option value="TWD">New Taiwan Dollar</option>
<option value="ZRN">New Zaire</option>
<option value="PLN">New Zloty</option>
<option value="KPW">North Korean Won</option>
<option value="NOK">Norwegian Krone</option>
<option value="PEN">Nuevo Sol</option>
<option value="MRO">Ouguiya</option>
<option value="PKR">Pakistan Rupee</option>
<option value="MOP">Pataca</option>
<option value="PHP">Philippine Peso</option>
<option value="BWP">Pula</option>
<option value="QAR">Qatari Rial</option>
<option value="GTQ">Quetzal</option>
<option value="ZAR">Rand</option>
<option value="BRL">Real</option>
<option value="OMR">Rial Omani</option>
<option value="MVR">Rufiyaa</option>
<option value="IDR">Rupiah</option>
<option value="RUB">Russian Ruble</option>
<option value="RWF">Rwanda Franc</option>
<option value="SAR">Saudi Riyal</option>
<option value="SCR">Seychelles Rupee</option>
<option value="ILS">Shekel</option>
<option value="SGD">Singapore Dollar</option>
<option value="SKK">Slovak Koruna</option>
<option value="SBD">Solomon Islands Dollar</option>
<option value="KGS">Som</option>
<option value="SOS">Somalia Shilling</option>
<option value="LKR">Sri Lanka Rupee</option>
<option value="SHP">St Helena Pound</option>
<option value="SDP">Sudanese Pound</option>
<option value="SRG">Suriname Guilder</option>
<option value="SZL">Swaziland Lilangeni</option>
<option value="SEK">Sweden Krona</option>
<option value="CHF">Swiss Franc</option>
<option value="SYP">Syrian Pound</option>
<option value="TJR">Tajik Ruble</option>
<option value="WST">Tala</option>
<option value="BDT">Taka</option>
<option value="TZS">Tanzanian Shilling</option>
<option value="KZT">Tenge</option>
<option value="TPE">Timor Escudo</option>
<option value="SIT">Tolar</option>
<option value="TOP">Tonga Pa\anga</option>
<option value="TTD">Trinidad &amp; Tobago Dollar</option>
<option value="TND">Tunisian Dinar</option>
<option value="TRY">Turkish Lira</option>
<option value="UGX">Uganda Shilling</option>
<option value="UAH">Ukrainian Hryvnia</option>
<option value="AED">United Arab Emirates Dirham</option>
<option value="UYU">Uruguayan Peso</option>
<option value="VUV">Vanuatu Vatu</option>
<option value="VEB">Venezuela Bolivar</option>
<option value="VND">Viet Nam Dong</option>
<option value="KRW">Won</option>
<option value="YER">Yemeni Rial</option>
<option value="JPY">Yen</option>
<option value="CNY">Yuan Renminbi</option>
<option value="YUM">Yugoslavian New Dinar</option>
<option value="ZMK">Zambian Kwacha</option>
<option value="ZWD">Zimbabwe Dollar</option>';

$paypal_currency_list = '<option value="AUD">Australian Dollar</option>
<option value="CAD">Canadian Dollar</option>  
<option value="DKK">Danish Krone</option>
<option value="EUR">Euro</option>
<option value="HKD">Hong Kong Dollar</option>
<option value="MXN">Mexico Peso</option>
<option value="NZD">New Zealand Dollar</option>
<option value="PLN">New Zloty</option>
<option value="NOK">Norwegian Krone</option>
<option value="GBP">Pounds Sterling</option>
<option value="ILS">Shekel</option>
<option value="SEK">Sweden Krona</option>
<option value="SGD">Singapore Dollar</option>
<option value="CHF">Swiss Franc</option>
<option value="USD">US Dollar</option>
<option value="JPY">Yen</option>';
?>